global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'server-pilot'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: '${SP_USER}'
      password: '${SP_PASS}'
    static_configs:
      - targets: ['server-pilot-backend:8090']
